# NumPy Assignment: Array Operations & Mathematical Functions

## Question 1: Fundamental NumPy Array Operations

### (a) Reverse the NumPy array: `arr = np.array([1, 2, 3, 6, 4, 5])`

In [1]:
# Import required libraries
import numpy as np
print("NumPy imported successfully!")

NumPy imported successfully!


In [2]:
# Create the original array
original_array = np.array([1, 2, 3, 6, 4, 5])

# Method to reverse the array using np.flip()
reversed_array = np.flip(original_array)

# Display results
print("Array Reversal Operation")
print("-" * 30)
print(f"Original Array  : {original_array}")
print(f"Reversed Array  : {reversed_array}")
print("-" * 30)

Array Reversal Operation
------------------------------
Original Array  : [1 2 3 6 4 5]
Reversed Array  : [5 4 6 3 2 1]
------------------------------


### (b) Flatten the NumPy array using two different methods

In [3]:
# Create a 2D array for flattening demonstration
matrix_2d = np.array([[1, 2, 3], 
                      [2, 4, 5], 
                      [1, 2, 3]])

print("Array Flattening Demonstration")
print("Original 2D Matrix:")
print(matrix_2d)
print()

# Method 1: Using flatten() - Returns a copy
flattened_copy = matrix_2d.flatten()
print("Method 1: Using flatten() (creates a copy)")
print(f"Result: {flattened_copy}")
print()

# Method 2: Using ravel() - Returns a view when possible
flattened_view = matrix_2d.ravel()
print("Method 2: Using ravel() (creates a view)")
print(f"Result: {flattened_view}")

Array Flattening Demonstration
Original 2D Matrix:
[[1 2 3]
 [2 4 5]
 [1 2 3]]

Method 1: Using flatten() (creates a copy)
Result: [1 2 3 2 4 5 1 2 3]

Method 2: Using ravel() (creates a view)
Result: [1 2 3 2 4 5 1 2 3]


### (c) Compare the NumPy arrays

In [4]:
# Create two identical arrays for comparison
first_matrix = np.array([[1, 2], 
                        [3, 4]])
second_matrix = np.array([[1, 2], 
                         [3, 4]])

print("Array Comparison Analysis")
print("First Matrix:")
print(first_matrix)
print("\nSecond Matrix:")
print(second_matrix)

# Perform array comparison
arrays_are_equal = np.array_equal(first_matrix, second_matrix)
print(f"\nComparison Result: Arrays are {'EQUAL' if arrays_are_equal else 'NOT EQUAL'}")

Array Comparison Analysis
First Matrix:
[[1 2]
 [3 4]]

Second Matrix:
[[1 2]
 [3 4]]

Comparison Result: Arrays are EQUAL


### (d) Find the most frequent value and their indices

In [5]:
# Import Counter for frequency analysis
from collections import Counter

# Define test arrays
dataset_x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
dataset_y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def analyze_frequency(arr, name):
    """Analyze frequency of elements in an array"""
    print(f"Analysis for {name}:")
    print(f"Array: {arr}")
    
    # Count frequencies
    frequency_count = Counter(arr)
    most_frequent_item = frequency_count.most_common(1)[0]
    frequent_value = most_frequent_item[0]
    
    # Find all indices of the most frequent value
    indices_locations = np.where(arr == frequent_value)[0]
    
    print(f"Most Frequent Value: {frequent_value}")
    print(f"Frequency Count: {most_frequent_item[1]}")
    print(f"Index Positions: {indices_locations}")
    print()

print("Frequency Analysis")
print("=" * 25)

# Analyze both arrays
analyze_frequency(dataset_x, "Dataset X")
analyze_frequency(dataset_y, "Dataset Y")

Frequency Analysis
Analysis for Dataset X:
Array: [1 2 3 4 5 1 2 1 1 1]
Most Frequent Value: 1
Frequency Count: 5
Index Positions: [0 5 7 8 9]

Analysis for Dataset Y:
Array: [1 1 1 2 3 4 2 4 3 3]
Most Frequent Value: 1
Frequency Count: 3
Index Positions: [0 1 2]



### (e) Matrix operations - Sum calculations

In [6]:
# Create matrix using np.matrix
sample_matrix = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

print("Matrix Sum Calculations")
print("Input Matrix:")
print(sample_matrix)
print()

# Calculate different types of sums
total_sum = np.sum(sample_matrix)
row_wise_sums = np.sum(sample_matrix, axis=1).flatten()
column_wise_sums = np.sum(sample_matrix, axis=0).flatten()

# Display results
print("Sum Analysis:")
print(f"i. Total Sum (all elements): {total_sum}")
print(f"ii. Row-wise Sums: {row_wise_sums}")
print(f"iii. Column-wise Sums: {column_wise_sums}")

Matrix Sum Calculations
Input Matrix:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

Sum Analysis:
i. Total Sum (all elements): 45
ii. Row-wise Sums: [[14 16 15]]
iii. Column-wise Sums: [[20  9 16]]


### (f) Matrix operations - Linear algebra

In [7]:
# Define a 3x3 matrix for linear algebra operations
test_matrix = np.array([[55, 25, 15], 
                       [30, 44, 2], 
                       [11, 45, 77]])

print("Linear Algebra Operations")
print("Input Matrix:")
print(test_matrix)
print()

# i. Diagonal sum (trace)
diagonal_sum = np.trace(test_matrix)
print(f"i. Sum of diagonal elements: {diagonal_sum}")

# ii. & iii. Eigenvalues and eigenvectors
eigen_vals, eigen_vecs = np.linalg.eig(test_matrix)
print(f"\nii. Eigenvalues:")
for i, val in enumerate(eigen_vals):
    print(f"    λ{i+1} = {val:.4f}")

print(f"\niii. Eigenvectors:")
print(eigen_vecs)

# iv. Matrix inverse
matrix_inverse = np.linalg.inv(test_matrix)
print(f"\niv. Inverse Matrix:")
print(matrix_inverse)

# v. Determinant
matrix_determinant = np.linalg.det(test_matrix)
print(f"\nv. Matrix Determinant: {matrix_determinant:.2f}")

Linear Algebra Operations
Input Matrix:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

i. Sum of diagonal elements: 176

ii. Eigenvalues:
    λ1 = 98.1684
    λ2 = 28.0970
    λ3 = 49.7346

iii. Eigenvectors:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

iv. Inverse Matrix:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

v. Matrix Determinant: 137180.00


### (g) Matrix multiplication and covariance

In [8]:
print("Matrix Multiplication & Covariance")
print("=" * 35)

# First pair of matrices
matrix_p1 = np.array([[1, 2], 
                     [2, 3]])
matrix_q1 = np.array([[4, 5], 
                     [6, 7]])

print("Set 1: Square Matrices")
print("Matrix P1 =")
print(matrix_p1)
print("Matrix Q1 =")
print(matrix_q1)

# Matrix multiplication for first set
multiplication_result1 = np.dot(matrix_p1, matrix_q1)
print("\nMatrix Multiplication (P1 @ Q1):")
print(multiplication_result1)

# Covariance calculation for first set
covariance_result1 = np.cov(matrix_p1.flatten(), matrix_q1.flatten())
print("Covariance Matrix:")
print(covariance_result1)

print("\n" + "-" * 35)

# Second pair of matrices  
matrix_p2 = np.array([[1, 2], 
                     [2, 3], 
                     [4, 5]])
matrix_q2 = np.array([[4, 5, 1], 
                     [6, 7, 2]])

print("Set 2: Rectangular Matrices")
print("Matrix P2 =")
print(matrix_p2)
print("Matrix Q2 =")
print(matrix_q2)

# Matrix multiplication for second set
multiplication_result2 = np.dot(matrix_p2, matrix_q2)
print("\nMatrix Multiplication (P2 @ Q2):")
print(multiplication_result2)

# Covariance calculation for second set
covariance_result2 = np.cov(matrix_p2.flatten(), matrix_q2.flatten())
print("Covariance Matrix:")
print(covariance_result2)

Matrix Multiplication & Covariance
Set 1: Square Matrices
Matrix P1 =
[[1 2]
 [2 3]]
Matrix Q1 =
[[4 5]
 [6 7]]

Matrix Multiplication (P1 @ Q1):
[[16 19]
 [26 31]]
Covariance Matrix:
[[0.66666667 1.        ]
 [1.         1.66666667]]

-----------------------------------
Set 2: Rectangular Matrices
Matrix P2 =
[[1 2]
 [2 3]
 [4 5]]
Matrix Q2 =
[[4 5 1]
 [6 7 2]]

Matrix Multiplication (P2 @ Q2):
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance Matrix:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


### (h) Inner, outer and cartesian products

In [9]:
# Define matrices for product operations
matrix_x = np.array([[2, 3, 4], 
                    [3, 2, 9]])
matrix_y = np.array([[1, 5, 0], 
                    [5, 10, 3]])

print("Product Operations Analysis")
print("Matrix X:")
print(matrix_x)
print("\nMatrix Y:")
print(matrix_y)
print()

# Inner Product Calculation
inner_product_result = np.inner(matrix_x, matrix_y)
print("Inner Product:")
print(inner_product_result)
print()

# Outer Product Calculation (using flattened arrays)
x_flattened = matrix_x.flatten()
y_flattened = matrix_y.flatten()
outer_product_result = np.outer(x_flattened, y_flattened)
print("Outer Product:")
print(outer_product_result)
print()

# Cartesian Product using meshgrid
print("Cartesian Product (using meshgrid):")
cartesian_x, cartesian_y = np.meshgrid(x_flattened, y_flattened)
cartesian_product = np.array([cartesian_x.flatten(), cartesian_y.flatten()]).T
print(f"Shape of Cartesian Product: {cartesian_product.shape}")
print("Sample pairs (first 10):")
print(cartesian_product[:10])

Product Operations Analysis
Matrix X:
[[2 3 4]
 [3 2 9]]

Matrix Y:
[[ 1  5  0]
 [ 5 10  3]]

Inner Product:
[[17 52]
 [13 62]]

Outer Product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian Product (using meshgrid):
Shape of Cartesian Product: (36, 2)
Sample pairs (first 10):
[[2 1]
 [3 1]
 [4 1]
 [3 1]
 [2 1]
 [9 1]
 [2 5]
 [3 5]
 [4 5]
 [3 5]]


## Question 2: Mathematical Functions & Statistical Analysis

### (a) Array operations - absolute value and percentiles

In [10]:
# Create a test array with positive and negative values
test_array = np.array([[1, -2, 3], 
                      [-4, 5, -6]])

print("Statistical Analysis Operations")
print("Original Array:")
print(test_array)
print()

# i. Element-wise absolute value calculation
absolute_values = np.abs(test_array)
print("i. Element-wise Absolute Values:")
print(absolute_values)
print()

# ii. Percentile calculations
flattened_data = test_array.flatten()
print("ii. Percentile Analysis:")
print(f"Flattened Data: {flattened_data}")
print()

# Calculate percentiles for flattened array
percentiles = [25, 50, 75]
print("Percentiles (Flattened Array):")
for p in percentiles:
    value = np.percentile(flattened_data, p)
    print(f"  {p}th percentile: {value}")
print()

# Calculate percentiles by columns
print("Percentiles (Column-wise):")
for p in percentiles:
    values = np.percentile(test_array, p, axis=0)
    print(f"  {p}th percentile: {values}")
print()

# Calculate percentiles by rows
print("Percentiles (Row-wise):")
for p in percentiles:
    values = np.percentile(test_array, p, axis=1)
    print(f"  {p}th percentile: {values}")
print()

# iii. Statistical measures
print("iii. Statistical Summary:")
print("Flattened Array Statistics:")
print(f"  Mean: {np.mean(flattened_data):.2f}")
print(f"  Median: {np.median(flattened_data):.2f}")
print(f"  Standard Deviation: {np.std(flattened_data):.2f}")
print()

print("Column-wise Statistics:")
print(f"  Mean: {np.mean(test_array, axis=0)}")
print(f"  Median: {np.median(test_array, axis=0)}")
print(f"  Standard Deviation: {np.std(test_array, axis=0)}")
print()

print("Row-wise Statistics:")
print(f"  Mean: {np.mean(test_array, axis=1)}")
print(f"  Median: {np.median(test_array, axis=1)}")
print(f"  Standard Deviation: {np.std(test_array, axis=1)}")

Statistical Analysis Operations
Original Array:
[[ 1 -2  3]
 [-4  5 -6]]

i. Element-wise Absolute Values:
[[1 2 3]
 [4 5 6]]

ii. Percentile Analysis:
Flattened Data: [ 1 -2  3 -4  5 -6]

Percentiles (Flattened Array):
  25th percentile: -3.5
  50th percentile: -0.5
  75th percentile: 2.5

Percentiles (Column-wise):
  25th percentile: [-2.75 -0.25 -3.75]
  50th percentile: [-1.5  1.5 -1.5]
  75th percentile: [-0.25  3.25  0.75]

Percentiles (Row-wise):
  25th percentile: [-0.5 -5. ]
  50th percentile: [ 1. -4.]
  75th percentile: [2.  0.5]

iii. Statistical Summary:
Flattened Array Statistics:
  Mean: -0.50
  Median: -0.50
  Standard Deviation: 3.86

Column-wise Statistics:
  Mean: [-1.5  1.5 -1.5]
  Median: [-1.5  1.5 -1.5]
  Standard Deviation: [2.5 3.5 4.5]

Row-wise Statistics:
  Mean: [ 0.66666667 -1.66666667]
  Median: [ 1. -4.]
  Standard Deviation: [2.05480467 4.78423336]


### (b) Floor, ceiling, truncated and rounded values

In [11]:
# Define array with decimal values for mathematical operations
decimal_array = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print("Mathematical Functions")
print(f"Original Array: {decimal_array}")
print()

# Apply different mathematical functions
print("Function Results:")
print(f"Floor values: {np.floor(decimal_array)}")
print(f"Ceiling values: {np.ceil(decimal_array)}")
print(f"Truncated values: {np.trunc(decimal_array)}")
print(f"Rounded values: {np.round(decimal_array)}")

Mathematical Functions
Original Array: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]

Function Results:
Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


## Question 3: Array Searching & Sorting Operations

### (a) Array sorting operations

In [12]:
# Create array for sorting demonstrations
unsorted_array = np.array([10, 52, 62, 16, 16, 54, 453])

print("Sorting Operations Demo")
print(f"Original Array: {unsorted_array}")
print()

# i. Sort the array
sorted_result = np.sort(unsorted_array)
print(f"i. Sorted Array: {sorted_result}")

# ii. Get indices that would sort the array
sort_indices = np.argsort(unsorted_array)
print(f"ii. Sorting Indices: {sort_indices}")

# iii. Find 4 smallest elements
k_smallest = 4
smallest_indices = np.argpartition(unsorted_array, k_smallest-1)[:k_smallest]
smallest_elements = np.sort(unsorted_array[smallest_indices])
print(f"iii. {k_smallest} Smallest Elements: {smallest_elements}")

# iv. Find 5 largest elements  
k_largest = 5
largest_indices = np.argpartition(unsorted_array, -k_largest)[-k_largest:]
largest_elements = np.sort(unsorted_array[largest_indices])[::-1]
print(f"iv. {k_largest} Largest Elements: {largest_elements}")

Sorting Operations Demo
Original Array: [ 10  52  62  16  16  54 453]

i. Sorted Array: [ 10  16  16  52  54  62 453]
ii. Sorting Indices: [0 3 4 1 5 2 6]
iii. 4 Smallest Elements: [10 16 16 52]
iv. 5 Largest Elements: [453  62  54  52  16]


### (b) Filter integer and float elements

In [13]:
# Array containing both integer and float values
mixed_array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

print("Element Filtering Operations")
print(f"Original Array: {mixed_array}")
print()

# i. Filter integer elements (whole numbers)
integer_condition = mixed_array == np.floor(mixed_array)
integer_only = mixed_array[integer_condition]
print(f"i. Integer Elements:")
print(f"  Condition: {integer_condition}")
print(f"  Result: {integer_only}")
print()

# ii. Filter float elements (non-whole numbers)  
float_condition = mixed_array != np.floor(mixed_array)
float_only = mixed_array[float_condition]
print(f"ii. Float Elements:")
print(f"  Condition: {float_condition}")
print(f"  Result: {float_only}")

Element Filtering Operations
Original Array: [1.  1.2 2.2 2.  3.  2. ]

i. Integer Elements:
  Condition: [ True False False  True  True  True]
  Result: [1. 2. 3. 2.]

ii. Float Elements:
  Condition: [False  True  True False False False]
  Result: [1.2 2.2]


## Question 4: Image Processing with NumPy

(a) Write a function named `img_to_array(path)` that reads an image and saves it as text file  
(b) Load the saved file into jupyter notebook

In [14]:
# Image Processing with NumPy
import numpy as np
from PIL import Image
import os

def img_to_array(image_path):
    """
    Function to convert an image to numpy array and save as text file
    
    Parameters:
    image_path (str): Path to the input image
    
    Returns:
    tuple: (numpy_array, output_filename) or None if error occurs
    """
    try:
        # Load the image
        image = Image.open(image_path)
        image_array = np.array(image)
        
        # Get base filename without extension
        base_filename = os.path.splitext(os.path.basename(image_path))[0]
        
        if len(image_array.shape) == 3:  # RGB Color Image
            output_filename = f"{base_filename}_rgb_array.txt"
            
            # Save RGB data with proper formatting
            with open(output_filename, 'w') as file:
                file.write(f"# RGB Image Array Data\n")
                file.write(f"# Image Shape: {image_array.shape}\n")
                file.write(f"# Format: R G B values per line\n")
                file.write("# " + "="*40 + "\n")
                
                # Write RGB values row by row
                for row in range(image_array.shape[0]):
                    for col in range(image_array.shape[1]):
                        r, g, b = image_array[row, col]
                        file.write(f"{r} {g} {b}\n")
                        
        else:  # Grayscale Image
            output_filename = f"{base_filename}_grayscale_array.txt"
            np.savetxt(output_filename, image_array, fmt='%d', 
                      header=f"Grayscale Image Array - Shape: {image_array.shape}")
        
        return image_array, output_filename
        
    except Exception as error:
        print(f"Error processing image: {error}")
        return None

# Part (a): Process the image
print("Image to Array Conversion")
print("=" * 30)

# Process the image (using the correct path)
image_file_path = "image.jpg"
conversion_result = img_to_array(image_file_path)

if conversion_result:
    img_data, saved_filename = conversion_result
    
    print(f"Image processed successfully!")
    print(f"Image Shape: {img_data.shape}")
    print(f"Data Type: {img_data.dtype}")
    print(f"Saved as: {saved_filename}")
    
    # Display file size information
    file_size = os.path.getsize(saved_filename)
    print(f"File Size: {file_size:,} bytes")
    
    if len(img_data.shape) == 3:
        total_pixels = img_data.shape[0] * img_data.shape[1]
        print(f"Total Pixels: {total_pixels:,}")
    
    print()

# Part (b): Load the saved file
print("Loading Saved Array Data")
print("=" * 25)

# Find available text files with array data
available_files = [f for f in os.listdir('.') if f.endswith('_array.txt') and 'image' in f]

if available_files:
    target_file = available_files[0]
    print(f"Loading file: {target_file}")
    
    if 'grayscale' in target_file:
        # Load grayscale array data
        loaded_data = np.loadtxt(target_file, dtype=int)
        print(f"Grayscale array loaded successfully!")
        print(f"Loaded Shape: {loaded_data.shape}")
        
        # Verify data integrity
        data_match = np.array_equal(img_data, loaded_data)
        print(f"Data Integrity: {'VERIFIED' if data_match else 'MISMATCH'}")
        
    else:
        # Load RGB array data
        print(f"Loading RGB data...")
        
        with open(target_file, 'r') as file:
            lines = file.readlines()
        
        # Parse RGB data (skip header lines)
        rgb_values = []
        for line in lines:
            if not line.startswith('#') and line.strip():
                r, g, b = map(int, line.strip().split())
                rgb_values.append([r, g, b])
        
        if rgb_values:
            # Reconstruct the original image array
            reconstructed_array = np.array(rgb_values).reshape(img_data.shape)
            print(f"RGB array reconstructed successfully!")
            print(f"Reconstructed Shape: {reconstructed_array.shape}")
            
            # Verify data integrity
            data_match = np.array_equal(img_data, reconstructed_array)
            print(f"Data Integrity: {'VERIFIED' if data_match else 'MISMATCH'}")
    
    print("Image processing workflow completed successfully!")
else:
    print("No array files found to load.")

Image to Array Conversion
Image processed successfully!
Image Shape: (630, 1200, 3)
Data Type: uint8
Saved as: image_rgb_array.txt
File Size: 9,158,885 bytes
Total Pixels: 756,000

Loading Saved Array Data
Loading file: image_rgb_array.txt
Loading RGB data...
Image processed successfully!
Image Shape: (630, 1200, 3)
Data Type: uint8
Saved as: image_rgb_array.txt
File Size: 9,158,885 bytes
Total Pixels: 756,000

Loading Saved Array Data
Loading file: image_rgb_array.txt
Loading RGB data...
RGB array reconstructed successfully!
Reconstructed Shape: (630, 1200, 3)
Data Integrity: VERIFIED
Image processing workflow completed successfully!
RGB array reconstructed successfully!
Reconstructed Shape: (630, 1200, 3)
Data Integrity: VERIFIED
Image processing workflow completed successfully!
